apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kark
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-kark@sha256:4fb87514cce8d353beb59f03a6d963184f7c38c8e3620ebe33b2014724454c2c
        name: my-nodejs
        resources: {}
status: {}
